version: "3.6"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # volumes:
    #   - ".:/app"
    #   - "/app/node_modules"
    ports:
      - 3000:80
    # command: ["npm", "start"]

